pipeline {
    agent {
        docker{
            image 'python:2.7.16-slim'
        }
    }

    
    stages{
        stage('build'){
            when{
               
                 changeset "**/vote/**"
            }
            steps{
                echo "compiling worker app"
                dir('worker'){
                    sh 'pip install -r requirements.txt'
                   
                }
                }
            }
        
         stage('test'){
            when{

                 changeset "**/vote/**"
            }
            steps{
               echo "running unit tests" 
               dir('worker'){
                    sh 'nosetests -v'

                }
            }
        }
                
    }
}
        
