pipeline {
    agent none
    agent {
        docker{
            image 'python:2.7.16-slim'
            args '-u root'
        }
    }

    
    stages{


        stage('build'){
            agent {
        docker{
            image 'python:2.7.16-slim'
            args '-u root'
        }
    }

            when{
               
                 changeset "**/vote/**"
                 branch 'master'
            }
            steps{
                echo "compiling worker app"
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                   
                }
                }
            }
        
         stage('test'){
             agent {
        docker{
            image 'python:2.7.16-slim'
            args '-u root'
        }
    }

            when{
               
                 changeset "**/vote/**"
                 branch 'master'
            }
            steps{
               echo "running unit tests" 
               dir('vote'){
                    sh 'pip install nose'
                    sh 'nosetests -v'

                }
            }
        }

        stage('docker package'){
           agent any
           when {
               changeset "**/vote/**"
               branch 'master'
           }
        
            steps{
                echo "docker package"
                 dir('vote'){
                    script{
                        docker.withRegistry('https://index.docker.io/v1/','dockerlogin') {
                            def workerImage = docker.build("lexarflash8g/vote:v${env.BUILD_ID}", "./")
                                workerImage.push()
                                workerImage.push("${env.BRANCH_NAME}")
                    }
                    }
                }
            }
        }
    
                
    }
}
        

// #comment
