pipeline {
    agent any
    
    stages{
        stage('build'){
            steps{
                echo "compiling worker app")
                dir('worker'){
                    sh 'mvn compile'
                }
                }
            }
        }
         stage('test'){
            steps{
               echo "running unit tests" 
               dir('worker'){
                    sh 'mvn clean test'
                }
            }
        }
         stage('package'){
            steps{
                echo "packaging worker app"
                 dir('worker'){
                    sh 'mvn package'
                }
            }
        }
    }
    
    
}