pipeline {
    agent any
    
    tools {
        maven 'maven'
    }
    stages{
        stage('build'){
            
            steps{
                echo "compiling worker app"
                dir('worker'){
                    sh 'mvn compile'
                }
                }
            }
        
         stage('test'){
     
            }
            steps{
               echo "running unit tests" 
               dir('worker'){
                    sh 'mvn clean test'
                }
            }
        }
         stage('package'){
      
        
            steps{
                echo "packaging worker app"
                 dir('worker'){
                    sh 'mvn package -dskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint:True
                }
            }
        }
    }
    }
    
// }

//       when{
//                  branch 'master'
//                  changeset "**/worker"