pipeline {
    agent any
    
    stages{
        stage('build'){
            when{
                 branch 'master'
                 changeset "**/worker"
            steps{
                echo "compiling worker app"
                dir('worker'){
                    sh 'mvn compile'
                }
                }
            }
        
         stage('test'){
            when{
                 branch 'master'
                 changeset "**/worker"
            steps{
               echo "running unit tests" 
               dir('worker'){
                    sh 'mvn clean test'
                }
            }
        }
         stage('package'){
            when{
                 branch 'master'
                 changeset "**/worker"
             }
            steps{
                echo "packaging worker app"
                 dir('worker'){
                    sh 'mvn package -dskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint:True
                }
            }
        }
    }
    
    
}